name: orya
favicon: null
layout_spectrum: 0.06682771979831159
typography_spectrum: 0.030815889593213797
title: Orya
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9639967391267419
  lightness: 0.9842840782366693
  saturation: 0.08021535445004702
  rhythmicContrast: 0.7726224912330508
purpose: []
